export const KEYWORD_MAP: Record<string, string> = {
  yap: "console.log",
  fr: "const",
  rn: "let",
  pov: "if",
  sike: "else",
  lowkey: "else if",
  spam: "while",
  bet: "return",
  cook: "function",
  drop: "new",
  no_cap: "true",
  cap: "false",
  npc: "null",
  idk: "undefined",
  steal: "import",
  plug: "export",
  main: "default",
  via: "from",
};
